title:            David Martínez-Rubio
description:      Welcome to my academic site.
# Your site's domain goes here. Leave localhost server or blank when working locally.
#url:              http://localhost:5000
#http://localhost:5000
url:              https://damaru2.github.io
disqus_shortname: damaru2

# Owner/author information
owner:
  name:           David Martínez-Rubio
  avatar:         david.png
  email:          david_martirubio @ hotmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  linkedin: david-martínez-rubio-a3b250140
  google_scholar: dMwpf-4AAAAJ
  github: damaru2
  cv: https://drive.google.com/file/d/1kMMZIIiaMkXM1yqYr2lD-qo-H_EZnsTN/view
# Analytics and webmaster tools stuff goes here
#google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Publications
    url: /publications/
  - title: Curriculum
    url: /cv/
  - title: About
    url: /
#  - title: Posts
#  url: /blog/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

syntax_highlighter_opts:
  line_numbers:
  line_numbers_start: 1
  tab_width: 4
  bold_every: 10
  css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
